[build]
    base = "/"
    command = "cd docs && yarn run build:prod"
    publish = "build/docs"

[build.environment]
    HUGO_VERSION = "0.145.0"
    NODE_VERSION = "22"

[context.dev]
    command = "cd docs && yarn run build"
