apiVersion: v1
kind: Secret
metadata:
  # Change the secret name to the same value as used for installing the Helm chart
  name: comentario-secrets
type: Opaque
stringData:
  secrets.yaml: |
    <paste the content of your secrets.yaml file here>
