baseURL: https://edge.docs.comentario.app/
languageCode: en
title: 'Comentario Documentation [edge]'

publishDir: ../build/docs

disableKinds:
  - RSS
  - sitemap

outputs:
  home:
    - HTML
    - JSON

defaultContentLanguage: en
defaultContentLanguageInSubdir: true
languages:
  en:
    weight: 1

module:
  hugoVersion:
    extended: true
    min: "0.145.0"
  mounts:
    - source: ../node_modules
      target: assets/node_modules
    - source: assets
      target: assets
    - source: ../node_modules/@fortawesome/fontawesome-free/webfonts
      target: static/webfonts
    - source: static
      target: static

markup:
  goldmark:
    parser:
      attribute:
        block: true
    renderer:
      unsafe: true
  highlight:
    style: monokailight

sectionPagesMenu: sidebar

params:
  description: 'Documentation for Comentario, the powerful commenting tool for web pages.'
  contactAction: 'https://formspree.io/f/mjvqwoaa'

services:
  googleAnalytics:
    id: 'G-03C68PL4NZ'

menu:
  # Will be lowercased in the template
  extNavbar:
    - identifier: demo
      url: 'https://demo.comentario.app'
      weight: 10
