#!/bin/sh

service_name="comentario.service"

# Make sure permissions are correct
fixPermissions() {
    chmod 0600 /etc/comentario/secrets.yaml
}

# Create necessary directories
createDirs() {
    mkdir -p --mode=0644 /var/lib/comentario ||:
}

reloadConfig() {
    printf "\033[32m* Reloading the service unit from disk\033[0m\n"
    systemctl daemon-reload ||:
}

restartService() {
    printf "\033[32m* (Re)starting service %s\033[0m\n" $service_name
    systemctl restart $service_name ||:
}

# Post Install of an clean install
cleanInstall() {
    createDirs
    fixPermissions
    reloadConfig

    printf "\033[32m* Enabling service %s\033[0m\n" $service_name
    systemctl unmask $service_name ||:
    systemctl preset $service_name ||:
    systemctl enable $service_name ||:

    restartService
}

# Post Install of an upgrade
upgrade() {
    fixPermissions
    reloadConfig
    restartService
}

# Check if this is a clean install or an upgrade
action="$1"
if [ "$1" = "configure" ] && [ -z "$2" ]; then
    # Alpine linux does not pass args, and deb passes $1=configure
    action="install"
elif [ "$1" = "configure" ] && [ -n "$2" ]; then
    # deb passes $1=configure $2=<current version>
    action="upgrade"
fi

case "$action" in
    "1" | "install")
        cleanInstall
        ;;
    "2" | "upgrade")
        upgrade
        ;;
    *)
        # $1 == version being installed
        printf "\033[32m* Alpine\033[0m"
        cleanInstall
        ;;
esac
