import { CountryNamePipe } from './country-name.pipe';

describe('CountryNamePipe', () => {

    let pipe: CountryNamePipe;

    beforeEach(() => pipe = new CountryNamePipe());

    it('is created', () => {
        expect(pipe).toBeTruthy();
    });

    [
        {in: undefined, want: ''},
        {in: null,      want: ''},
        {in: '',        want: ''},
        {in: '*',       want: '[*]'},
        {in: 'AD',      want: 'Andorra'},
        {in: 'AE',      want: 'United Arab Emirates'},
        {in: 'AF',      want: 'Afghanistan'},
        {in: 'AG',      want: 'Antigua and Barbuda'},
        {in: 'AI',      want: 'Anguilla'},
        {in: 'AL',      want: 'Albania'},
        {in: 'AM',      want: 'Armenia'},
        {in: 'AN',      want: 'Netherlands Antilles'},
        {in: 'AO',      want: 'Angola'},
        {in: 'AQ',      want: 'Antarctica'},
        {in: 'AR',      want: 'Argentina'},
        {in: 'AS',      want: 'American Samoa'},
        {in: 'AT',      want: 'Austria'},
        {in: 'AU',      want: 'Australia'},
        {in: 'AW',      want: 'Aruba'},
        {in: 'AZ',      want: 'Azerbaijan'},
        {in: 'BA',      want: 'Bosnia and Herzegovina'},
        {in: 'BB',      want: 'Barbados'},
        {in: 'BD',      want: 'Bangladesh'},
        {in: 'BE',      want: 'Belgium'},
        {in: 'BF',      want: 'Burkina Faso'},
        {in: 'BG',      want: 'Bulgaria'},
        {in: 'BH',      want: 'Bahrain'},
        {in: 'BI',      want: 'Burundi'},
        {in: 'BJ',      want: 'Benin'},
        {in: 'BL',      want: 'Saint Barthélemy'},
        {in: 'BM',      want: 'Bermuda'},
        {in: 'BN',      want: 'Brunei'},
        {in: 'BO',      want: 'Bolivia'},
        {in: 'BR',      want: 'Brazil'},
        {in: 'BS',      want: 'Bahamas'},
        {in: 'BT',      want: 'Bhutan'},
        {in: 'BW',      want: 'Botswana'},
        {in: 'BY',      want: 'Belarus'},
        {in: 'BZ',      want: 'Belize'},
        {in: 'CA',      want: 'Canada'},
        {in: 'CC',      want: 'Cocos Islands'},
        {in: 'CD',      want: 'Democratic Republic of the Congo'},
        {in: 'CF',      want: 'Central African Republic'},
        {in: 'CG',      want: 'Republic of the Congo'},
        {in: 'CH',      want: 'Switzerland'},
        {in: 'CI',      want: 'Ivory Coast'},
        {in: 'CK',      want: 'Cook Islands'},
        {in: 'CL',      want: 'Chile'},
        {in: 'CM',      want: 'Cameroon'},
        {in: 'CN',      want: 'China'},
        {in: 'CO',      want: 'Colombia'},
        {in: 'CR',      want: 'Costa Rica'},
        {in: 'CU',      want: 'Cuba'},
        {in: 'CV',      want: 'Cape Verde'},
        {in: 'CW',      want: 'Curacao'},
        {in: 'CX',      want: 'Christmas Island'},
        {in: 'CY',      want: 'Cyprus'},
        {in: 'CZ',      want: 'Czech Republic'},
        {in: 'DE',      want: 'Germany'},
        {in: 'DJ',      want: 'Djibouti'},
        {in: 'DK',      want: 'Denmark'},
        {in: 'DM',      want: 'Dominica'},
        {in: 'DO',      want: 'Dominican Republic'},
        {in: 'DZ',      want: 'Algeria'},
        {in: 'EC',      want: 'Ecuador'},
        {in: 'EE',      want: 'Estonia'},
        {in: 'EG',      want: 'Egypt'},
        {in: 'EH',      want: 'Western Sahara'},
        {in: 'ER',      want: 'Eritrea'},
        {in: 'ES',      want: 'Spain'},
        {in: 'ET',      want: 'Ethiopia'},
        {in: 'FI',      want: 'Finland'},
        {in: 'FJ',      want: 'Fiji'},
        {in: 'FK',      want: 'Falkland Islands'},
        {in: 'FM',      want: 'Micronesia'},
        {in: 'FO',      want: 'Faroe Islands'},
        {in: 'FR',      want: 'France'},
        {in: 'GA',      want: 'Gabon'},
        {in: 'GB',      want: 'United Kingdom'},
        {in: 'GD',      want: 'Grenada'},
        {in: 'GE',      want: 'Georgia'},
        {in: 'GG',      want: 'Guernsey'},
        {in: 'GH',      want: 'Ghana'},
        {in: 'GI',      want: 'Gibraltar'},
        {in: 'GL',      want: 'Greenland'},
        {in: 'GM',      want: 'Gambia'},
        {in: 'GN',      want: 'Guinea'},
        {in: 'GQ',      want: 'Equatorial Guinea'},
        {in: 'GR',      want: 'Greece'},
        {in: 'GT',      want: 'Guatemala'},
        {in: 'GU',      want: 'Guam'},
        {in: 'GW',      want: 'Guinea-Bissau'},
        {in: 'GY',      want: 'Guyana'},
        {in: 'HK',      want: 'Hong Kong'},
        {in: 'HN',      want: 'Honduras'},
        {in: 'HR',      want: 'Croatia'},
        {in: 'HT',      want: 'Haiti'},
        {in: 'HU',      want: 'Hungary'},
        {in: 'ID',      want: 'Indonesia'},
        {in: 'IE',      want: 'Ireland'},
        {in: 'IL',      want: 'Israel'},
        {in: 'IM',      want: 'Isle of Man'},
        {in: 'IN',      want: 'India'},
        {in: 'IO',      want: 'British Indian Ocean Territory'},
        {in: 'IQ',      want: 'Iraq'},
        {in: 'IR',      want: 'Iran'},
        {in: 'IS',      want: 'Iceland'},
        {in: 'IT',      want: 'Italy'},
        {in: 'JE',      want: 'Jersey'},
        {in: 'JM',      want: 'Jamaica'},
        {in: 'JO',      want: 'Jordan'},
        {in: 'JP',      want: 'Japan'},
        {in: 'KE',      want: 'Kenya'},
        {in: 'KG',      want: 'Kyrgyzstan'},
        {in: 'KH',      want: 'Cambodia'},
        {in: 'KI',      want: 'Kiribati'},
        {in: 'KM',      want: 'Comoros'},
        {in: 'KN',      want: 'Saint Kitts and Nevis'},
        {in: 'KP',      want: 'North Korea'},
        {in: 'KR',      want: 'South Korea'},
        {in: 'KW',      want: 'Kuwait'},
        {in: 'KY',      want: 'Cayman Islands'},
        {in: 'KZ',      want: 'Kazakhstan'},
        {in: 'LA',      want: 'Laos'},
        {in: 'LB',      want: 'Lebanon'},
        {in: 'LC',      want: 'Saint Lucia'},
        {in: 'LI',      want: 'Liechtenstein'},
        {in: 'LK',      want: 'Sri Lanka'},
        {in: 'LR',      want: 'Liberia'},
        {in: 'LS',      want: 'Lesotho'},
        {in: 'LT',      want: 'Lithuania'},
        {in: 'LU',      want: 'Luxembourg'},
        {in: 'LV',      want: 'Latvia'},
        {in: 'LY',      want: 'Libya'},
        {in: 'MA',      want: 'Morocco'},
        {in: 'MC',      want: 'Monaco'},
        {in: 'MD',      want: 'Moldova'},
        {in: 'ME',      want: 'Montenegro'},
        {in: 'MF',      want: 'Saint Martin'},
        {in: 'MG',      want: 'Madagascar'},
        {in: 'MH',      want: 'Marshall Islands'},
        {in: 'MK',      want: 'Macedonia'},
        {in: 'ML',      want: 'Mali'},
        {in: 'MM',      want: 'Myanmar'},
        {in: 'MN',      want: 'Mongolia'},
        {in: 'MO',      want: 'Macau'},
        {in: 'MP',      want: 'Northern Mariana Islands'},
        {in: 'MR',      want: 'Mauritania'},
        {in: 'MS',      want: 'Montserrat'},
        {in: 'MT',      want: 'Malta'},
        {in: 'MU',      want: 'Mauritius'},
        {in: 'MV',      want: 'Maldives'},
        {in: 'MW',      want: 'Malawi'},
        {in: 'MX',      want: 'Mexico'},
        {in: 'MY',      want: 'Malaysia'},
        {in: 'MZ',      want: 'Mozambique'},
        {in: 'NA',      want: 'Namibia'},
        {in: 'NC',      want: 'New Caledonia'},
        {in: 'NE',      want: 'Niger'},
        {in: 'NG',      want: 'Nigeria'},
        {in: 'NI',      want: 'Nicaragua'},
        {in: 'NL',      want: 'Netherlands'},
        {in: 'NO',      want: 'Norway'},
        {in: 'NP',      want: 'Nepal'},
        {in: 'NR',      want: 'Nauru'},
        {in: 'NU',      want: 'Niue'},
        {in: 'NZ',      want: 'New Zealand'},
        {in: 'OM',      want: 'Oman'},
        {in: 'PA',      want: 'Panama'},
        {in: 'PE',      want: 'Peru'},
        {in: 'PF',      want: 'French Polynesia'},
        {in: 'PG',      want: 'Papua New Guinea'},
        {in: 'PH',      want: 'Philippines'},
        {in: 'PK',      want: 'Pakistan'},
        {in: 'PL',      want: 'Poland'},
        {in: 'PM',      want: 'Saint Pierre and Miquelon'},
        {in: 'PN',      want: 'Pitcairn'},
        {in: 'PR',      want: 'Puerto Rico'},
        {in: 'PS',      want: 'Palestine'},
        {in: 'PT',      want: 'Portugal'},
        {in: 'PW',      want: 'Palau'},
        {in: 'PY',      want: 'Paraguay'},
        {in: 'QA',      want: 'Qatar'},
        {in: 'RE',      want: 'Reunion'},
        {in: 'RO',      want: 'Romania'},
        {in: 'RS',      want: 'Serbia'},
        {in: 'RU',      want: 'Russia'},
        {in: 'RW',      want: 'Rwanda'},
        {in: 'SA',      want: 'Saudi Arabia'},
        {in: 'SB',      want: 'Solomon Islands'},
        {in: 'SC',      want: 'Seychelles'},
        {in: 'SD',      want: 'Sudan'},
        {in: 'SE',      want: 'Sweden'},
        {in: 'SG',      want: 'Singapore'},
        {in: 'SH',      want: 'Saint Helena'},
        {in: 'SI',      want: 'Slovenia'},
        {in: 'SJ',      want: 'Svalbard and Jan Mayen'},
        {in: 'SK',      want: 'Slovakia'},
        {in: 'SL',      want: 'Sierra Leone'},
        {in: 'SM',      want: 'San Marino'},
        {in: 'SN',      want: 'Senegal'},
        {in: 'SO',      want: 'Somalia'},
        {in: 'SR',      want: 'Suriname'},
        {in: 'SS',      want: 'South Sudan'},
        {in: 'ST',      want: 'Sao Tome and Principe'},
        {in: 'SV',      want: 'El Salvador'},
        {in: 'SX',      want: 'Sint Maarten'},
        {in: 'SY',      want: 'Syria'},
        {in: 'SZ',      want: 'Swaziland'},
        {in: 'TC',      want: 'Turks and Caicos Islands'},
        {in: 'TD',      want: 'Chad'},
        {in: 'TG',      want: 'Togo'},
        {in: 'TH',      want: 'Thailand'},
        {in: 'TJ',      want: 'Tajikistan'},
        {in: 'TK',      want: 'Tokelau'},
        {in: 'TL',      want: 'East Timor'},
        {in: 'TM',      want: 'Turkmenistan'},
        {in: 'TN',      want: 'Tunisia'},
        {in: 'TO',      want: 'Tonga'},
        {in: 'TR',      want: 'Turkey'},
        {in: 'TT',      want: 'Trinidad and Tobago'},
        {in: 'TV',      want: 'Tuvalu'},
        {in: 'TW',      want: 'Taiwan'},
        {in: 'TZ',      want: 'Tanzania'},
        {in: 'UA',      want: 'Ukraine'},
        {in: 'UG',      want: 'Uganda'},
        {in: 'US',      want: 'United States'},
        {in: 'UY',      want: 'Uruguay'},
        {in: 'UZ',      want: 'Uzbekistan'},
        {in: 'VA',      want: 'Vatican'},
        {in: 'VC',      want: 'Saint Vincent and the Grenadines'},
        {in: 'VE',      want: 'Venezuela'},
        {in: 'VG',      want: 'British Virgin Islands'},
        {in: 'VI',      want: 'U.S. Virgin Islands'},
        {in: 'VN',      want: 'Vietnam'},
        {in: 'VU',      want: 'Vanuatu'},
        {in: 'WF',      want: 'Wallis and Futuna'},
        {in: 'WS',      want: 'Samoa'},
        {in: 'XK',      want: 'Kosovo'},
        {in: 'YE',      want: 'Yemen'},
        {in: 'YT',      want: 'Mayotte'},
        {in: 'ZA',      want: 'South Africa'},
        {in: 'ZM',      want: 'Zambia'},
        {in: 'ZW',      want: 'Zimbabwe'},
        {in: 'ZZ',      want: '[ZZ]'},
    ]
        .forEach(test =>
            it(`transforms '${test.in}' into '${test.want}'`, () =>
                expect(pipe.transform(test.in)).toEqual(test.want)));
});
