#!/bin/bash
#=======================================================================================================================
# Build and start the Comentario backend in the end-2-end testing mode
#=======================================================================================================================

set -e

root_dir="$(dirname "$(dirname "$(realpath "$0")")")"
build_dir="$root_dir/build"

# Show usage info and exit
usage() {
    cat <<EOF >&2
Usage: $0 [options] [[--] backend_args]
Options:
  -B  skip build
  -D  skip (re)starting database
  -E  run Comentario NOT in end-2-end testing mode
  -G  skip OpenAPI code generation
  -d  enable DB debug logging
  -h  show usage info and exit
EOF
    exit 0
}

# Parse the command line
declare -i do_build=1 do_db=1 do_e2e=1 do_gen=1
comentario_args=
args=$(getopt -o BDEGdh -- "$@")
[[ $? -ne 0 ]] && usage
eval set -- $args
for i; do
    case "$i" in
        -B)
            do_build=0
            shift
            ;;
        -D)
            do_db=0
            shift
            ;;
        -E)
            do_e2e=0
            shift
            ;;
        -G)
            do_gen=0
            shift
            ;;
        -d)
            comentario_args="$comentario_args --db-debug"
            shift
            ;;
        -h)
            usage
            ;;
        --)
            shift;
            break
            ;;
    esac
done

# Make sure destination dir exists
mkdir -p "$build_dir"

# Remove any leftovers from previous builds
rm -rf "$build_dir/db" "$build_dir/templates"

# Build the backend
((do_gen))   && go generate
((do_build)) &&
    rm -f "$build_dir/comentario" &&
    echo "Building comentario" &&
    go build -o "$build_dir/comentario" -ldflags "-X main.version=$(git describe --tags | sed 's/^v//') -X main.date=$(date --iso-8601=seconds)"

# Build the e2e plugin
((do_build)) &&
    echo "Building e2e plugin" &&
    go build -buildmode=plugin -o "$build_dir/comentario-e2e.so" "$root_dir/e2e/plugin/"

# Build the e2e relay
((do_build)) &&
    echo "Building e2e relay" &&
    go build -o "$build_dir/comentario-relay" "$root_dir/e2e/relay/"

# (Re)start the database
if ((do_db)); then
    docker compose -f "$root_dir/docker-compose.yml" down -v
    docker compose -f "$root_dir/docker-compose.yml" up -d

    # Remove any SQLite DB
    rm -f "$build_dir/comentario.sqlite"
fi

# Copy required assets
echo "Copying assets to $build_dir"
cp -r "$root_dir/db/" "$root_dir/templates/" "$build_dir"

# Use the (local) ~secrets.yaml file if it's present, otherwise the "stock" secrets.postgres.yaml
secrets="$root_dir/resources/k8s/~secrets.yaml"
[[ ! -f "$secrets" ]] && secrets="$root_dir/resources/k8s/secrets.postgres.yaml"
echo "Using secrets file: $secrets"

# Add Claro plugin if present
[[ -d "$root_dir/../claro/build" ]] && comentario_args="$comentario_args --plugin-path=$root_dir/../claro/build"

# Start the backend
((do_e2e)) && comentario_args="$comentario_args --e2e"
echo "Starting $build_dir/comentario"
"$build_dir/comentario" $comentario_args \
    -vv \
    --port=8080 \
    --static-path="$build_dir/frontend" \
    --db-migration-path="$build_dir/db" \
    --template-path="$build_dir/templates" \
    --secrets="$secrets" \
    --base-docs-url="https://edge.docs.comentario.app" \
    --home-content-url="https://edge.docs.comentario.app/en/embed/front-page/" \
    "$@"
